#!/bin/bash
# Build a flashable payload image from this running system.
#
# The output is one file that turns a bare Pi 5 + NVMe into a working camera
# payload: kernel module, device tree overlay, the locally built libcamera with
# the AR1335 CamHelper, the radcam package, the STP link, and every tool. That
# matters more than it sounds - the libcamera build in /usr/local took real
# effort to get right and is not reproducible from a package list.
#
# It is built by rsync into a fresh filesystem rather than by copying blocks,
# for three reasons: the size is chosen rather than inherited (a 465 GB disk
# does not need a 465 GB image), the exclusions are explicit and reviewable,
# and a running filesystem can be read consistently enough this way while a
# block copy of one cannot.
#
#   sudo tools/build-payload-image.sh [--out DIR] [--margin GB] [--no-compress]
#
# Produces radcam-payload-<date>.img.gz plus a .sha256 next to it.
set -euo pipefail

OUT_DIR=/home/rad/images
MARGIN_GB=2
COMPRESS=1
KEEP_MOUNTED=0

while [ $# -gt 0 ]; do
    case "$1" in
        --out) OUT_DIR="$2"; shift 2 ;;
        --margin) MARGIN_GB="$2"; shift 2 ;;
        --no-compress) COMPRESS=0; shift ;;
        -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

[ "$(id -u)" -eq 0 ] || { echo "run with sudo" >&2; exit 1; }

STAMP=$(date +%Y%m%d-%H%M)
IMG="$OUT_DIR/radcam-payload-$STAMP.img"
MNT=/mnt/radcam-image
BOOT_SRC=/boot/firmware

# --------------------------------------------------------------------------
# What does not travel.
#
# Three categories, and the distinction matters when reviewing this list:
#   - identity: regenerated on first boot, wrong if cloned
#   - per-Pi measurement: the dosimeter lives on the Pi, not on the camera
#     module, so its calibration cannot be inherited by another board
#   - bulk with no flight value: caches, editors, captures, swap
# --------------------------------------------------------------------------
EXCLUDES=(
    # -- pseudo-filesystems -------------------------------------------------
    /proc/* /sys/* /dev/* /run/* /tmp/* /mnt/* /media/* /lost+found

    # -- identity: regenerated by radcam-firstboot.sh -----------------------
    /etc/machine-id
    /var/lib/dbus/machine-id
    /etc/ssh/ssh_host_*

    # -- per-Pi state -------------------------------------------------------
    # The dosimeter is an LTC2485 on the Pi, so its calibration describes THIS
    # board and would be a quietly wrong number on any other one. Shipping it
    # is worse than shipping nothing: an uncalibrated payload says so, a
    # miscalibrated one reports confident bad dose figures.
    /var/lib/radcam/dosimeter-cal.json.*
    /var/lib/radcam/dose-log.bin
    /var/lib/radcam/boot-count
    /var/lib/radcam/media/*
    /var/lib/radcam/slots/*
    /var/log/radcam/*

    # -- development environment, not flight software -----------------------
    /home/rad/.vscode-server
    /home/rad/.local/share
    /home/rad/.claude
    /home/rad/.claude.json*
    /home/rad/.bash_history
    /home/rad/.dotnet
    /root/.bash_history
    /etc/sudoers.d/claude-autonomy
    /home/rad/.config/systemd/user/claude-*

    # -- rebuildable or worthless bulk --------------------------------------
    /var/swap
    /var/cache/apt/archives/*
    /var/log/*.gz /var/log/*.[0-9] /var/log/journal/*
    /home/rad/driver-dev/captures/*
    /home/rad/driver-dev/logs/*
    /home/rad/driver-dev/libcamera-src
    /home/rad/driver-dev/**/__pycache__
    /home/rad/images
)

echo "=== radcam payload image builder ==="
echo "    source : this running system ($(hostname))"
echo "    output : $IMG"
echo

# -- size ------------------------------------------------------------------
# Measure what will actually be copied rather than guessing, then add margin
# so the first boot has room before it expands.
echo "--- measuring"
EXCL_ARGS=()
for e in "${EXCLUDES[@]}"; do EXCL_ARGS+=(--exclude="$e"); done

USED_KB=$(rsync -a --dry-run --stats "${EXCL_ARGS[@]}" / /tmp/nonexistent-target 2>/dev/null \
          | awk '/Total file size:/ {gsub(/,/,"",$4); print int($4/1024)}' || echo 0)
if [ "${USED_KB:-0}" -lt 1000000 ]; then
    # Fall back to du if rsync's dry run did not give us a usable number.
    USED_KB=$(du -sx --exclude=/proc --exclude=/sys --exclude=/dev --exclude=/run \
                 --exclude=/tmp --exclude=/var/swap --exclude=/home/rad/.vscode-server \
                 --exclude=/home/rad/.local/share --exclude=/home/rad/driver-dev/captures \
                 / 2>/dev/null | cut -f1)
fi
USED_GB=$(( USED_KB / 1024 / 1024 + 1 ))
ROOT_GB=$(( USED_GB + MARGIN_GB ))
BOOT_MB=512
TOTAL_MB=$(( BOOT_MB + ROOT_GB * 1024 + 8 ))
echo "    payload ~${USED_GB} GB, root partition ${ROOT_GB} GB, image ${TOTAL_MB} MB"

mkdir -p "$OUT_DIR"

# -- partition -------------------------------------------------------------
# The MBR disk identifier is set to match the live system's, so the PARTUUIDs
# in /etc/fstab and cmdline.txt are copied verbatim and are correct on the
# clone. Getting this wrong is the classic way a cloned Pi boots to a
# rootwait timeout with no useful message.
DISK_ID=$(fdisk -l /dev/nvme0n1 2>/dev/null | awk '/Disk identifier/ {print $3}' | sed 's/^0x//')
DISK_ID=${DISK_ID:-a1b2c3d4}
echo "--- creating image (disk identifier 0x$DISK_ID)"

rm -f "$IMG"
truncate -s "${TOTAL_MB}M" "$IMG"

sfdisk "$IMG" >/dev/null <<EOF
label: dos
label-id: 0x$DISK_ID
unit: sectors
start=8192, size=$(( BOOT_MB * 2048 )), type=c, bootable
start=$(( 8192 + BOOT_MB * 2048 )), type=83
EOF

LOOP=$(losetup --show -fP "$IMG")
trap 'set +e; umount -R "$MNT" 2>/dev/null; losetup -d "$LOOP" 2>/dev/null' EXIT
echo "    $LOOP"

mkfs.vfat -F 32 -n bootfs "${LOOP}p1" >/dev/null
mkfs.ext4 -q -L rootfs -m 1 "${LOOP}p2"

mkdir -p "$MNT"
mount "${LOOP}p2" "$MNT"
mkdir -p "$MNT/boot/firmware"
mount "${LOOP}p1" "$MNT/boot/firmware"

# -- copy ------------------------------------------------------------------
# Progress output only when a person is watching. Piped to a file or a log,
# --info=progress2 emits a line per file and buries the useful output.
if [ -t 1 ]; then PROGRESS=(--info=progress2); else PROGRESS=(); fi

echo "--- copying root filesystem"
rsync -aHAXx "${PROGRESS[@]}" "${EXCL_ARGS[@]}" \
      --exclude=/boot/firmware/* \
      / "$MNT/"

echo "--- copying boot partition"
rsync -rltD "${PROGRESS[@]}" "$BOOT_SRC/" "$MNT/boot/firmware/"

# Directories the excludes emptied still have to exist.
mkdir -p "$MNT"/{proc,sys,dev,run,tmp,mnt,media} \
         "$MNT/var/lib/radcam"/{media,slots} "$MNT/var/log/radcam"
chmod 1777 "$MNT/tmp"

# -- sanitise --------------------------------------------------------------
echo "--- sanitising the clone"

# machine-id must exist and be empty, not absent: systemd treats an empty file
# as "first boot" and populates it, while a missing one is an error on some
# paths.
: > "$MNT/etc/machine-id"
rm -f "$MNT/var/lib/dbus/machine-id"
ln -sf /etc/machine-id "$MNT/var/lib/dbus/machine-id"

# The development conveniences on this Pi have no place on a flight unit.
# Passwordless sudo in particular: it exists so an agent can work unattended,
# and it should not be the security posture of five deployed payloads.
rm -f "$MNT/etc/sudoers.d/claude-autonomy"
rm -rf "$MNT/home/rad/.config/systemd/user"

# A clone that remembers this Pi's wifi is a clone that joins this network.
find "$MNT/etc/NetworkManager/system-connections" -type f -delete 2>/dev/null || true

# -- first boot ------------------------------------------------------------
echo "--- installing first-boot provisioning"
install -m 755 /home/rad/driver-dev/provisioning/radcam-firstboot.sh \
        "$MNT/usr/local/sbin/radcam-firstboot.sh"
install -m 644 /home/rad/driver-dev/provisioning/radcam-firstboot.service \
        "$MNT/etc/systemd/system/radcam-firstboot.service"
mkdir -p "$MNT/etc/systemd/system/sysinit.target.wants"
ln -sf ../radcam-firstboot.service \
       "$MNT/etc/systemd/system/sysinit.target.wants/radcam-firstboot.service"
rm -f "$MNT/var/lib/radcam/.firstboot-done"

# The image ships with no unit number and an obviously unprovisioned hostname.
# Defaulting to 1 would mean a drive somebody forgot to stamp comes up as a
# silent duplicate of the build machine - two radcam1s on a bench with five
# units is a genuinely confusing hour.
echo "radcam-unconfigured" > "$MNT/etc/hostname"
# Rewrite the 127.0.1.1 line rather than substituting into it: this system's
# copy has the hostname twice, and a textual substitution would faithfully
# reproduce that oddity onto five more units.
sed -i '/^127\.0\.1\.1/d' "$MNT/etc/hosts"
printf '127.0.1.1\tradcam-unconfigured\n' >> "$MNT/etc/hosts"

# The unit number sits on the FAT partition so it can be set from any machine,
# Windows included, without mounting ext4.
cat > "$MNT/boot/firmware/radcam-unit.txt" <<'EOF'
# Put this payload's unit number on the line below: a single digit, nothing
# else. The payload comes up as radcam<N>. Until it is set, the unit boots as
# "radcam-unconfigured" so an unstamped drive is obvious rather than a
# duplicate of another unit.

EOF
cat > "$MNT/boot/firmware/radcam-README.txt" <<'EOF'
radcam payload image
====================

Set this unit's number by editing radcam-unit.txt on THIS partition: put a
single digit on the first line. The payload becomes radcam<N> on first boot.
Do this before the first boot; afterwards, use hostnamectl.

The dosimeter is calibrated per Pi, not per camera module, so a freshly
flashed unit has no dose calibration. Run `sudo radcamctl calibrate` on it.
Camera colour calibration DOES travel, because it lives on the camera
module's own EEPROM - swapping modules between units carries it along.
EOF

sync
umount -R "$MNT"
losetup -d "$LOOP"
trap - EXIT

# -- publish ---------------------------------------------------------------
if [ "$COMPRESS" -eq 1 ]; then
    echo "--- compressing (this is the slow part)"
    gzip -1 -f "$IMG"
    IMG="$IMG.gz"
fi

sha256sum "$IMG" > "$IMG.sha256"
echo
echo "=== done ==="
ls -lh "$IMG" "$IMG.sha256" | sed 's/^/    /'
echo
echo "Flash it with:"
echo "    sudo tools/flash-payload-image.sh $IMG /dev/sdX --unit 2"
echo "or with Raspberry Pi Imager -> Use custom -> $(basename "$IMG")"
