#!/usr/bin/env python3
"""Generate the AR1335 mode register tables for our driver.

Source of truth is NXP's GPL-2.0 isp-vvcam AR1335 driver, vendored under
docs/reference/nxp-ar1335/. Those headers hold the onsemi "recommended
settings" sequences, which cannot be derived or guessed. Transcribing ~930
register writes by hand would be error-prone, so we convert them mechanically
instead and keep this script as the record of how it was done.

Re-run with:  python3 tools/gen-regs.py
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "docs" / "reference" / "nxp-ar1335"
OUT = ROOT / "kernel" / "ar1335" / "ar1335_modes.h"

# source header -> (our table name, human description)
TABLES = [
    ("ar1335_regs_12MP.h", "ar1335_mode_4096x3072_regs",
     "4096x3072 (12 MP), 25 fps, RAW10, 4 lanes, 468 MHz link"),
    ("ar1335_regs_1080p.h", "ar1335_mode_1920x1080_30fps_regs",
     "1920x1080 2x2 binned, 30 fps, RAW10, 4 lanes, 439.2 MHz link"),
    ("ar1335_regs_1080p60.h", "ar1335_mode_1920x1080_60fps_regs",
     "1920x1080 2x2 binned, 60 fps, RAW10, 4 lanes, 439.2 MHz link"),
]

REG_RE = re.compile(
    r"^\s*\{\s*(0x[0-9A-Fa-f]{4})\s*,\s*(0x[0-9A-Fa-f]{1,4})\s*\}\s*,"
    r"\s*(?:/\*\s*(.*?)\s*\*/)?"
)

# RESET_REGISTER. The vendor sequences finish by setting bit 2 (streaming on);
# we drop that so the driver owns start/stop through s_stream.
RESET_REGISTER = 0x301A
STREAM_BIT = 0x0004


def parse(path):
    regs = []
    for line in path.read_text(errors="replace").splitlines():
        m = REG_RE.match(line)
        if m:
            addr = int(m.group(1), 16)
            val = int(m.group(2), 16)
            regs.append((addr, val, m.group(3) or ""))
    return regs


def main():
    if not SRC.is_dir():
        sys.exit(f"reference sources missing: {SRC}")

    out = [
        "/* SPDX-License-Identifier: GPL-2.0 */",
        "/*",
        " * AR1335 mode register tables.",
        " *",
        " * AUTO-GENERATED by tools/gen-regs.py - do not edit by hand.",
        " *",
        " * Derived from NXP's GPL-2.0 isp-vvcam AR1335 driver",
        " * (github.com/nxp-imx/isp-vvcam, vvcam/v4l2/sensor/ar1335), which",
        " * carries the onsemi recommended-settings sequences.",
        " *",
        " * Copyright (C) 2012-2015 Freescale Semiconductor, Inc.",
        " * Copyright 2018 NXP",
        " * Copyright (c) 2020 VeriSilicon Holdings Co., Ltd.",
        " *",
        " * All sequences assume a 24 MHz EXTCLK.",
        " */",
        "",
        "#ifndef _AR1335_MODES_H_",
        "#define _AR1335_MODES_H_",
        "",
        "#include <media/v4l2-cci.h>",
        "",
    ]

    total = 0
    for src, name, desc in TABLES:
        path = SRC / src
        if not path.is_file():
            sys.exit(f"missing reference header: {path}")
        regs = parse(path)
        if not regs:
            sys.exit(f"no registers parsed from {path}")

        # Drop a trailing stream-enable write if the vendor list ends with one.
        while regs and regs[-1][0] == RESET_REGISTER and regs[-1][1] & STREAM_BIT:
            regs.pop()

        out.append(f"/* {desc} */")
        out.append(f"static const struct cci_reg_sequence {name}[] = {{")
        for addr, val, comment in regs:
            entry = f"\t{{ CCI_REG16(0x{addr:04X}), 0x{val:04X} }},"
            if comment:
                entry = f"{entry:<44}/* {comment} */"
            out.append(entry)
        out.append("};")
        out.append("")
        total += len(regs)
        print(f"{name:<38} {len(regs):>4} registers  (from {src})")

    out.append("#endif /* _AR1335_MODES_H_ */")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out) + "\n")
    print(f"\nwrote {OUT}  ({total} registers total)")


if __name__ == "__main__":
    main()
