#!/usr/bin/env python3
"""Prove the payload transmits correct STP, byte by byte, on the real link.

Two things are easy to confuse and this separates them. That the code builds
valid packets is a unit-test question, already answered elsewhere. What this
answers is whether the *flight path* - the real Experiment, driven by real
requests, over the real UART - puts ICD-conformant bytes on the wire at the
configured rate.

So it drives an actual Experiment through a capture link, takes the exact bytes
it chose to emit, and checks each field against the interface control document:
sizes, sync, packet type, target, and the CRC-16 over the range the ICD
specifies. Then it transmits those same bytes through the real transceiver and
confirms the driver held for the packet's duration, which is what proves the
bits reached the line rather than merely the FIFO.

It also checks the three disciplines that matter on a shared bus, because a
payload that gets these wrong corrupts other experiments rather than merely
failing: silence when not polled, ignoring a foreign Target ID, and rejecting a
bad envelope CRC.

    sudo systemctl stop radcamd
    sudo tools/stp-txverify.py
    sudo systemctl start radcamd
"""
import struct, sys, time, zlib
sys.path.insert(0, "/home/rad/driver-dev")
from radcam.protocol import Config as ProtoConfig, Dispatcher, Msg
from radcam.stp import hrt as H, lrt as L, packets as P
from radcam.stp.commands import encode_command_payload
from radcam.stp.experiment import Experiment, ExperimentConfig, StpOp
from radcam.stp.link import Rs422Link, NullDeLine
from radcam.slots import SlotStore, SLOT_IMAGE
from tests.support import MemoryLink
import tempfile, os

TARGET = 0xC7
WIRE = P.Wire(target_id=TARGET)
fails = []

def check(name, ok, detail=""):
    print(f"  {'PASS' if ok else 'FAIL'}  {name}" + (f"   {detail}" if detail else ""))
    if not ok: fails.append(name)

# --- drive the REAL experiment over a capture link -------------------------
tmp = tempfile.mkdtemp()
slots = SlotStore(tmp, count=16)
slots.store(3, bytes(range(256)) * 12, SLOT_IMAGE, 640, 480)   # 3072 B
cap = MemoryLink()
exp = Experiment(link=cap, wire=WIRE,
                 dispatcher=Dispatcher(config=ProtoConfig()), slots=slots,
                 config=ExperimentConfig(target_id=TARGET, scrub_interval_s=3600))
exp.start()

def drain():
    raw = cap.dice_read(); out=[]; i=0
    while i < len(raw):
        at = raw.find(WIRE.sync_bytes, i)
        if at < 0 or at+6 > len(raw): break
        t = raw[at+4]
        n = 8 if t==0x10 else 1256 if t==0x81 else 1288 if t==0x87 else 0
        if not n or at+n > len(raw): break
        out.append(raw[at:at+n]); i = at+n
    return out

print("=" * 72)
print("STP PROTOCOL VERIFICATION  (generated by the real flight code path)")
print("=" * 72)

# 1. Command -> ACK
print("\n1. COMMAND ACK  (ICD: type 0x10, 8 bytes, DICE<-Experiment)")
cap.dice_send(P.encode_command(encode_command_payload(Msg.PING, 1), 0, 0, WIRE, TARGET))
exp.service(); time.sleep(0.3)
pkts = drain(); ack = pkts[0]
check("size is 8 bytes", len(ack) == P.COMMAND_ACK_SIZE, f"{len(ack)}")
check("sync 1ACFFC1D at offset 0", ack[0:4] == bytes.fromhex("1acffc1d"), ack[0:4].hex().upper())
check("packet type 0x10 at offset 4", ack[4] == 0x10, f"0x{ack[4]:02X}")
check("target 0xC7 at offset 5", ack[5] == TARGET, f"0x{ack[5]:02X}")
check("CRC in final 2 bytes", WIRE.check_crc(ack, 6), ack[6:8].hex().upper())
check("CRC covers packet[4:6]", WIRE.crc.compute(ack[4:6]) == WIRE.crc.unpack(ack[6:8]))
print(f"        bytes: {ack.hex(' ').upper()}")

# 2. LRT request -> LRT data
print("\n2. LRT DATA  (ICD: type 0x81, 1256 bytes, 624-word payload)")
cap.dice_send(P.encode_short_request(P.PacketType.LRT_REQUEST, 0, 0, WIRE, TARGET))
exp.service()
lrt = [p for p in drain() if p[4] == 0x81][0]
check("size is 1256 bytes", len(lrt) == P.LRT_DATA_PACKET_SIZE, f"{len(lrt)}")
check("sync at offset 0", lrt[0:4] == bytes.fromhex("1acffc1d"))
check("packet type 0x81 at offset 4", lrt[4] == 0x81, f"0x{lrt[4]:02X}")
check("target 0xC7 at offset 5", lrt[5] == TARGET, f"0x{lrt[5]:02X}")
check("data field is 1248 B (624 words)", P.LRT_DATA_LENGTH == 1248)
check("CRC in final 2 bytes, over packet[4:1254]", WIRE.check_crc(lrt, 1254), lrt[1254:1256].hex().upper())
body = L.decode_lrt_payload(lrt[6:6+1248])
check("payload CRC-32 valid", body["payload_crc_ok"])
check("payload echoes target 0xC7", body["target_id"] == TARGET, f"0x{body['target_id']:02X}")
check("format version 1", body["format_version"] == 1)
check("slot table reported", body["slot_count"] == 16 and body["slots_used"] == 1,
      f"{body['slots_used']}/{body['slot_count']} used")
print(f"        header: {lrt[:16].hex(' ').upper()} ...")

# 3. Slot download -> HRT
print("\n3. HRT DATA  (ICD: type 0x87, 1288 bytes, 640-word payload)")
cap.dice_send(P.encode_command(encode_command_payload(StpOp.SLOT_DOWNLOAD, 2, bytes([3])), 0,0, WIRE, TARGET))
exp.service(); time.sleep(0.4); cap.dice_read()
cap.dice_send(P.encode_short_request(P.PacketType.HRT_GO, 0, 0, WIRE, TARGET))
exp.service()
hrts = [p for p in drain() if p[4] == 0x87]
check("HRT packets emitted after HRT Go", len(hrts) > 0, f"{len(hrts)} packets")
h = hrts[0]
check("size is 1288 bytes", len(h) == P.HRT_DATA_PACKET_SIZE, f"{len(h)}")
check("packet type 0x87 at offset 4", h[4] == 0x87, f"0x{h[4]:02X}")
check("target 0xC7 at offset 5", h[5] == TARGET, f"0x{h[5]:02X}")
check("data field is 1280 B (640 words)", P.HRT_DATA_LENGTH == 1280)
check("CRC in final 2 bytes, over packet[4:1286]", WIRE.check_crc(h, 1286), h[1286:1288].hex().upper())
hb = H.decode_hrt_payload(h[6:6+1280])
check("sub-type MEDIA_INFO first", hb["sub_type"] == H.SubType.MEDIA_INFO, f"0x{hb['sub_type']:04X}")
check("chunk CRC-32 valid", hb["data_crc_ok"])
info = H.decode_media_info(hb["data"])
check("media id is the slot namespace 0x510000NN", (info["media_id"] & 0xFFFFFF00) == 0x51000000,
      f"0x{info['media_id']:08X}")
data_pkts = [p for p in hrts if H.decode_hrt_payload(p[6:6+1280])["sub_type"] == H.SubType.MEDIA_DATA]
check("MEDIA_DATA chunks follow", len(data_pkts) > 0, f"{len(data_pkts)} chunks")
check("all chunk CRC-32 valid", all(H.decode_hrt_payload(p[6:6+1280])["data_crc_ok"] for p in data_pkts))
print(f"        header: {h[:16].hex(' ').upper()} ...")

# 4. Discipline
print("\n4. PROTOCOL DISCIPLINE")
cap.dice_read()
for _ in range(5): exp.service()
check("silent when not polled", len(cap.dice_read()) == 0)
cap.dice_send(P.encode_command(encode_command_payload(Msg.PING, 9), 0,0, WIRE, 0x42))
exp.service()
check("ignores a foreign Target ID (0x42)", len(cap.dice_read()) == 0)
bad = bytearray(P.encode_command(encode_command_payload(Msg.PING, 10), 0,0, WIRE, TARGET)); bad[50] ^= 0xFF
cap.dice_send(bytes(bad)); exp.service()
check("rejects a bad envelope CRC", len(cap.dice_read()) == 0)
exp.stop()

# --- now transmit those exact bytes on the real hardware -------------------
print("\n5. TRANSMISSION ON THE REAL RS-422 LINK AT 921600")
link = Rs422Link(port="/dev/ttyAMA0", baud=921600, de=NullDeLine(release_gpio=4))
link.open()
for name, pkt in (("Command ACK", ack), ("LRT Data", lrt), ("HRT Data", h)):
    t0 = time.perf_counter(); ok = link.send(pkt); dt = time.perf_counter()-t0
    wire_s = len(pkt)*10/921600
    check(f"{name} transmitted ({len(pkt)} B)", ok,
          f"wire {wire_s*1e3:.2f} ms, held {dt*1e3:.2f} ms, excess {(dt-wire_s)*1e6:.0f} us")
print(f"        link stats: {link.stats()}")
link.close()

print("\n" + "=" * 72)
print(f"{'ALL CHECKS PASSED' if not fails else str(len(fails)) + ' FAILED: ' + ', '.join(fails)}")
print("=" * 72)
sys.exit(1 if fails else 0)
